### ISSUE TITLE
Sprint 2 review

### ISSUE THREAD

**Issue by rachelhisko** [rachelchrisjeremy/web-app#20]
Explanations of what each team member did
How did you & the sprint succeed? What was positive?
How did you & the sprint fail? What was negative

**Comment by rachelhisko** [comment]
We nearly finished our sprints for this week. We had to go through our user stories at the becoming of class. We should have done more tasks during the sprint so we don't feel rushed in our third sprint. 

What I did
**Competitive analysis**
-found 4 apps that are the competition
-wrote explanations for each app (why they were successful and what wasn't successful)

**Comment by jeremyahkupo** [comment]
Jeremy- Wrote user stories based on our app definition station.
Rachel- Found competitors based on our app idea
Chris- Wrote up personas
The sprint succeeded by keeping track of what was needed to be done. We probably should have completed a few more tasks on the Web App UI page so we didn't feel as rushed this week.

**Comment by chris-hough** [comment]
I completed a pair of personas to further develop our target audience.

**Comment by jeremyahkupo** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
The Sprint reviews should be more personal, discussing what *you* did instead of the team as a whole. Try to use "I" sentences instead of "We" sentences.

---

The Sprint 2 Issues are pretty good, but could be broken down a little more. Instead of saying "Create 2 personas", maybe use a todo list within the Issue:

```md
- [ ] Create Leia persona
- [ ] Create Chewie persona
```

Don’t forget to close the Project board now that the Sprint is complete.
