### ISSUE TITLE
UX Rubric 

### ISSUE THREAD

**Issue by rachelhisko** [rachelchrisjeremy/web-app#6]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Teamwork Quality** | Tasks were very badly divided and distributed. | Tasks were divided poorly. | Tasks divided fairly. | Tasks were perfectly divided among team members. |
| **Sprint Planning** | Sprints weren't managed. | Sprints were managed poorly. | Sprints managed fairly well. | Sprints were managed and kept up to date by all team members. |
| **Quality personas** | No personas. | Some personas developed. | Persona developed fairly well. | Personas developed fully. |
| **Research** | No research. | Some research provided. | A fair amount of research provided. | Disturbing amount of research. |
| **Website goals & value proposition** | No Website goals & value proposition. | Website goals & value proposition somewhat completed. |  Website goals & value proposition completed. |  Website goals & value proposition is thoroughly completed. |
| **Competitive analysis** | No Competitive analysis. | Competitive analysis somewhat completed. |  Website goals & value proposition completed. |  Competitive analysis is thoroughly completed. |
| **Sketched Wireframes** | No wireframes. | Wireframes somewhat completed. |  Wireframes completed. |  Wireframes are thoroughly completed. |
| **Interactive Wireframes** | No interactive wireframes. | Interactive wireframes somewhat completed. |  Interactive wireframes completed. |  Interactive wireframes are thoroughly completed. |

**Comment by jeremyahkupo** [comment]
Teamwork Quality: **3** - Our team manages tasks between us very clearly and efficiently. We worked closely together to ensure that everything was divided equally
Sprint Planning: **3** - We have planed every sprints for each week and divided the issues up so that they are very specific problems.  
Quality personas: **3** - The personas were fully complete and edited to match our app's brand. 
Research: **3** - Our team did a disturbing amount of research to ensure that we understood our app fully. We went through the design thinking process first defining our problem and creating a solution for it by using; empathy maps, user stories, etc. 
Website goals & value proposition: **3** - Written out in detail and thoroughly thought out.
Competitive analysis: **3** - Competitors were researched and assessed thoroughly to make sure we had original and innovative ideas.
Sketched wireframes: **3** - Wireframes were sketched in detail to guide our interactive plans.
Interactive Wireframes: **3** - Done on XD with a great amount of detail. Everything links and ensures the feeling of a real prototyped app.
